const surgeryList = [
    { label: 'Extracción de material de osteosíntesis' },
    { label: 'Colocación de placa en 8' },
    { label: 'Reduccion y Osteosintesis' },
    { label: 'Operación de Nuss' },
    { label: 'Cirugía de Turco' },
    { label: 'Biopsia' },
    { label: 'Limpieza quirúrgica' },
    { label: 'Artroscopia de rodilla' },
    { label: 'Colocación de clavo endomedular' },
    { label: 'Tenotomía' },
    { label: 'Cierre de ileostomía' },
    { label: 'Hernioplastia' },
    { label: 'Laparotomía exploradora' },
    { label: 'Laparoscopia exploradora' },
    { label: 'Colecistectomía' },
    { label: 'Orquidopexia' },
    { label: 'Gastrostomía' },
    { label: 'Apendicectomía' },
    { label: 'Plástica' },
    { label: 'Postioplastia' },
    { label: 'Pieloplastia' },
    { label: 'Uretroplastia' },
    { label: 'Nefrectomía' },
    { label: 'Genitoplastia' },
    { label: 'Reimplante vesicoureteral' },
];

export default surgeryList;